# Generated by Django 5.1.5 on 2025-03-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
